name: Build and Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: jsumners/gh-action-hugo-deploy@v1.0.0
        with:
          destination_repo: jrwrigh/jrwrigh.github.io
          destination_token: ${{ secrets.TOKEN }}
